/**
 * Receipt quick-add golden-set evaluation (plan §7 — the accuracy instrument).
 *
 * Replays the committed SYNTHETIC receipt corpus (scripts/golden/receipts/, generated by
 * makeGoldenReceipts.ts) through the SAME system prompt, tool schema, few-shot exemplar,
 * response picker, and sanitizer the deployed function uses (imported, not copied — the eval
 * cannot drift from prod), against the live Anthropic API, and scores field-by-field against
 * the manifest's expected values. Money (cost) is reported as a separate sub-score. Run it
 * before and after ANY change to the prompt, schema, or model pin; a drop is a regression
 * regardless of how plausible the change looked.
 *
 *   cd CloudFunctions && npx tsx scripts/receiptGoldenEval.ts                # prod config
 *   npx tsx scripts/receiptGoldenEval.ts --variant no-fewshot               # few-shot A/B
 *   npx tsx scripts/receiptGoldenEval.ts --runs 3                           # 3 samples/case
 *   npx tsx scripts/receiptGoldenEval.ts --model claude-sonnet-4-6          # tier comparison
 *
 * Pre-registered gates (plan §7): ship gate >=90% overall field accuracy on Haiku; escalate the
 * model tier only if prompt iteration plateaus <90% overall, or a costlier model beats Haiku by
 * >5 points on the money sub-score. Death condition D1 (plan §13): <85% overall even on
 * claude-sonnet-4-6, or money <90% on both tiers, kills the feature before any client build.
 *
 * Requires ANTHROPIC_API_KEY in the environment (source CloudFunctions/.env; never echo it).
 * NOW is pinned so the date line and the sanitizer's future-date clamp have a fixed truth.
 * Full JSON report lands in ../../reports/receipt-golden-<variant>.json; stdout is the
 * scoreboard only.
 */
import {
  RECEIPT_ENTRY_TOOL,
  SYSTEM_PROMPT,
  receiptFewShotMessages,
  referenceDateLine,
  sanitizeReceiptProposal,
  toolInputFromPayload,
} from "../src/functions/receiptQuickAdd";
import * as fs from "fs";
import * as path from "path";

// Tuesday, matching the receiptQuickAdd test clock. Every corpus date is on or before this day.
const NOW = new Date("2026-07-28T17:00:00Z");

const CORPUS_DIR = path.join(__dirname, "golden", "receipts");

interface GoldenExpect {
  documentLooksLikeReceipt: boolean;
  entryType?: string[];
  cost?: number | null;
  odometerReading?: number | null;
  shopName?: string | null;
  entryDay?: string | null;
  isDiy?: boolean | null;
  lineItemsContain?: string[];
}

interface GoldenCase {
  id: string;
  kind: "images" | "pdf";
  files: string[];
  description: string;
  expect: GoldenExpect;
}

interface Manifest { renderer: string; cases: GoldenCase[] }

interface FieldResult { field: string; expected: unknown; got: unknown; pass: boolean }
interface CaseResult { id: string; run: number; fields: FieldResult[]; raw: unknown }

function loadManifest(): Manifest {
  const manifestPath = path.join(CORPUS_DIR, "manifest.json");
  if (!fs.existsSync(manifestPath)) {
    console.error(`missing ${manifestPath} — run: npx tsx scripts/makeGoldenReceipts.ts`);
    process.exit(1);
  }
  const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8")) as Manifest;
  if (manifest.renderer === "svg-only") {
    console.error("corpus is svg-only (no Chrome was available at generation time).");
    console.error("Manual step: render scripts/golden/receipts/svg/*.svg to same-size JPEGs");
    console.error("(and pdf-invoice.svg to PDF) into scripts/golden/receipts/, then rerun");
    console.error("makeGoldenReceipts.ts with Chrome installed — or place the files manually.");
    process.exit(1);
  }
  return manifest;
}

function sourceBlocks(c: GoldenCase): unknown[] {
  return c.files.map((file) => {
    const data = fs.readFileSync(path.join(CORPUS_DIR, file)).toString("base64");
    return c.kind === "pdf"
      ? { type: "document", source: { type: "base64", media_type: "application/pdf", data } }
      : { type: "image", source: { type: "base64", media_type: "image/jpeg", data } };
  });
}

/**
 * Scores one case. Money (cost) rows are tallied into a separate sub-score by the caller.
 * For the non-receipt control only the documentLooksLikeReceipt verdict is scored — prod
 * turns it into the typed not_a_receipt error before any field reaches the client.
 */
function scoreCase(c: GoldenCase, raw: Record<string, unknown>): FieldResult[] {
  const out: FieldResult[] = [];
  const push = (field: string, expected: unknown, got: unknown, pass: boolean) =>
    out.push({ field, expected, got, pass });

  const saidReceipt = raw.documentLooksLikeReceipt !== false;
  push("documentLooksLikeReceipt", c.expect.documentLooksLikeReceipt, saidReceipt,
    saidReceipt === c.expect.documentLooksLikeReceipt);
  if (!c.expect.documentLooksLikeReceipt) return out;

  const proposal = sanitizeReceiptProposal(raw, NOW) as unknown as Record<string, unknown>;

  if (c.expect.entryType !== undefined) {
    push("entryType", c.expect.entryType.join("|"), proposal.entryType,
      c.expect.entryType.includes(String(proposal.entryType)));
  }
  if (c.expect.cost !== undefined) {
    push("cost", c.expect.cost, proposal.cost,
      proposal.cost === c.expect.cost || (c.expect.cost === null && proposal.cost == null));
  }
  if (c.expect.odometerReading !== undefined) {
    push("odometerReading", c.expect.odometerReading, proposal.odometerReading,
      proposal.odometerReading === c.expect.odometerReading ||
      (c.expect.odometerReading === null && proposal.odometerReading == null));
  }
  if (c.expect.shopName !== undefined) {
    const got = typeof proposal.shopName === "string" ? proposal.shopName : null;
    const pass = c.expect.shopName === null
      ? got === null
      : got !== null && got.toLowerCase().includes(String(c.expect.shopName).toLowerCase());
    push("shopName", c.expect.shopName, got, pass);
  }
  if (c.expect.entryDay !== undefined) {
    const got = typeof proposal.entryDate === "string" ? proposal.entryDate.slice(0, 10) : null;
    push("entryDay", c.expect.entryDay, got, got === c.expect.entryDay);
  }
  if (c.expect.isDiy !== undefined) {
    push("isDiy", c.expect.isDiy, proposal.isDiy,
      proposal.isDiy === c.expect.isDiy || (c.expect.isDiy === null && proposal.isDiy == null));
  }
  if (c.expect.lineItemsContain !== undefined && c.expect.lineItemsContain.length > 0) {
    const joined = Array.isArray(proposal.lineItems)
      ? (proposal.lineItems as string[]).join(" | ").toLowerCase()
      : "";
    for (const needle of c.expect.lineItemsContain) {
      push(`lineItems~${needle}`, needle, joined || null, joined.includes(needle.toLowerCase()));
    }
  }
  return out;
}

/**
 * Prompt variants under test. "no-fewshot" is the pre-registered A/B (plan §1): the exemplar
 * is TEXT-transcribed, and whether it transfers to vision is validated here, never assumed.
 * "no-date-line" measures what the anchored system date line is worth on printed documents.
 */
const VARIANTS: Record<string, { system: string; fewshot: boolean }> = {
  "prod": { system: SYSTEM_PROMPT + referenceDateLine(NOW), fewshot: true },
  "no-fewshot": { system: SYSTEM_PROMPT + referenceDateLine(NOW), fewshot: false },
  "no-date-line": { system: SYSTEM_PROMPT, fewshot: true },
};

async function callModel(
  c: GoldenCase,
  variant: { system: string; fewshot: boolean },
  apiKey: string,
  model: string,
): Promise<Record<string, unknown>> {
  const finalMessage = {
    role: "user",
    content: [
      ...sourceBlocks(c),
      { type: "text", text: "Extract this vehicle service receipt into a log entry." },
    ],
  };
  const response = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: { "content-type": "application/json", "x-api-key": apiKey, "anthropic-version": "2023-06-01" },
    body: JSON.stringify({
      model,
      max_tokens: 1024,
      system: variant.system,
      tools: [RECEIPT_ENTRY_TOOL],
      tool_choice: { type: "tool", name: RECEIPT_ENTRY_TOOL.name },
      messages: variant.fewshot ? [...receiptFewShotMessages(NOW), finalMessage] : [finalMessage],
    }),
  });
  if (!response.ok) {
    // Print ONLY the API's own error message (no request echo, no user data, no headers).
    let apiMessage = "";
    try {
      const body = await response.json() as { error?: { message?: string } };
      apiMessage = typeof body.error?.message === "string" ? ` — ${body.error.message}` : "";
    } catch {
      // body unavailable; status alone will have to do
    }
    throw new Error(`API ${response.status} on ${c.id}${apiMessage}`);
  }
  const payload = await response.json();
  const parsed = toolInputFromPayload(payload);
  if (!parsed) throw new Error(`no tool_use block on ${c.id}`);
  return parsed;
}

async function main(): Promise<void> {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) { console.error("ANTHROPIC_API_KEY not set"); process.exit(1); }
  const variantFlag = process.argv.indexOf("--variant");
  const variant = variantFlag >= 0 ? process.argv[variantFlag + 1] : "prod";
  const spec = VARIANTS[variant];
  if (!spec) { console.error(`unknown variant; use one of: ${Object.keys(VARIANTS).join(", ")}`); process.exit(1); }
  const runsFlag = process.argv.indexOf("--runs");
  const runs = runsFlag >= 0 ? Number(process.argv[runsFlag + 1]) || 1 : 1;
  const modelFlag = process.argv.indexOf("--model");
  const model = modelFlag >= 0 ? process.argv[modelFlag + 1] : "claude-haiku-4-5";

  const manifest = loadManifest();
  const results: CaseResult[] = [];
  let pass = 0, total = 0;
  let moneyPass = 0, moneyTotal = 0;
  for (const c of manifest.cases) {
    for (let run = 1; run <= runs; run += 1) {
      const raw = await callModel(c, spec, apiKey, model);
      const fields = scoreCase(c, raw);
      results.push({ id: c.id, run, fields, raw });
      for (const field of fields) {
        total += 1;
        if (field.pass) pass += 1;
        if (field.field === "cost") {
          moneyTotal += 1;
          if (field.pass) moneyPass += 1;
        }
      }
      const casePass = fields.filter((f) => f.pass).length;
      const failed = fields.filter((f) => !f.pass)
        .map((f) => `${f.field}(exp ${JSON.stringify(f.expected)} got ${JSON.stringify(f.got)})`);
      console.log(`${c.id} run${run}: ${casePass}/${fields.length}${failed.length ? "  FAIL " + failed.join(", ") : ""}`);
    }
  }
  const pct = (p: number, t: number): string => (t === 0 ? "n/a" : `${((100 * p) / t).toFixed(1)}%`);
  console.log(`\n[${variant}] TOTAL ${pass}/${total} fields (${pct(pass, total)})`);
  console.log(`[${variant}] MONEY ${moneyPass}/${moneyTotal} cost fields (${pct(moneyPass, moneyTotal)})`);

  const reportDir = path.join(__dirname, "..", "..", "reports");
  fs.mkdirSync(reportDir, { recursive: true });
  const suffix = model === "claude-haiku-4-5" ? "" : `-${model}`;
  const file = path.join(reportDir, `receipt-golden-${variant}${suffix}.json`);
  fs.writeFileSync(file, JSON.stringify({
    variant, model, runs, now: NOW.toISOString(),
    pass, total, moneyPass, moneyTotal, results,
  }, null, 1));
  console.log(`report: ${file}`);
}

main().catch((error) => { console.error(error); process.exit(1); });
