/**
 * Receipt quick-add golden-set evaluation (plan §7 — the accuracy instrument).
 *
 * Replays the committed SYNTHETIC receipt corpus (scripts/golden/receipts/, generated by
 * makeGoldenReceipts.ts) through the SAME system prompt, tool schema, few-shot exemplar,
 * response picker, and sanitizer the deployed function uses (imported, not copied — the eval
 * cannot drift from prod), against the live Anthropic API, and scores field-by-field against
 * the manifest's expected values. Money (cost) is reported as a separate sub-score. Run it
 * before and after ANY change to the prompt, schema, or model pin; a drop is a regression
 * regardless of how plausible the change looked.
 *
 *   cd CloudFunctions && npx tsx scripts/receiptGoldenEval.ts                # prod config
 *   npx tsx scripts/receiptGoldenEval.ts --variant no-fewshot               # few-shot A/B
 *   npx tsx scripts/receiptGoldenEval.ts --runs 3                           # 3 samples/case
 *   npx tsx scripts/receiptGoldenEval.ts --model claude-sonnet-4-6          # tier comparison
 *
 * Pre-registered gates (plan §7): ship gate >=90% overall field accuracy on Haiku; escalate the
 * model tier only if prompt iteration plateaus <90% overall, or a costlier model beats Haiku by
 * >5 points on the money sub-score. Death condition D1 (plan §13): <85% overall even on
 * claude-sonnet-4-6, or money <90% on both tiers, kills the feature before any client build.
 *
 * Requires ANTHROPIC_API_KEY in the environment (source CloudFunctions/.env; never echo it).
 * NOW is pinned so the date line and the sanitizer's future-date clamp have a fixed truth.
 * Full JSON report lands in ../../reports/receipt-golden-<variant>.json; stdout is the
 * scoreboard only.
 */
import {
  RECEIPT_ENTRY_TOOL,
  SYSTEM_PROMPT,
  extractReceiptTypedDetails,
  receiptFewShotMessages,
  referenceDateLine,
  sanitizeReceiptProposal,
  toolInputFromPayload,
} from "../src/functions/receiptQuickAdd";
import type { ReceiptPayload } from "../src/functions/receiptQuickAdd";
import { typedFieldsFor } from "../src/functions/typedExtraction";
import type { EntryTypeValue, TypedDetails } from "../src/functions/typedExtraction";
import * as fs from "fs";
import * as path from "path";

// Tuesday, matching the receiptQuickAdd test clock. Every corpus date is on or before this day.
const NOW = new Date("2026-07-28T17:00:00Z");

const CORPUS_DIR = path.join(__dirname, "golden", "receipts");

interface GoldenExpect {
  documentLooksLikeReceipt: boolean;
  entryType?: string[];
  cost?: number | null;
  odometerReading?: number | null;
  shopName?: string | null;
  entryDay?: string | null;
  isDiy?: boolean | null;
  lineItemsContain?: string[];
}

interface GoldenCase {
  id: string;
  kind: "images" | "pdf";
  files: string[];
  description: string;
  expect: GoldenExpect;
}

interface Manifest { renderer: string; cases: GoldenCase[] }

interface FieldResult { field: string; expected: unknown; got: unknown; pass: boolean }
interface CaseResult { id: string; run: number; fields: FieldResult[]; raw: unknown }

function loadManifest(): Manifest {
  const manifestPath = path.join(CORPUS_DIR, "manifest.json");
  if (!fs.existsSync(manifestPath)) {
    console.error(`missing ${manifestPath} — run: npx tsx scripts/makeGoldenReceipts.ts`);
    process.exit(1);
  }
  const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8")) as Manifest;
  if (manifest.renderer === "svg-only") {
    console.error("corpus is svg-only (no Chrome was available at generation time).");
    console.error("Manual step: render scripts/golden/receipts/svg/*.svg to same-size JPEGs");
    console.error("(and pdf-invoice.svg to PDF) into scripts/golden/receipts/, then rerun");
    console.error("makeGoldenReceipts.ts with Chrome installed — or place the files manually.");
    process.exit(1);
  }
  return manifest;
}

function sourceBlocks(c: GoldenCase): unknown[] {
  return c.files.map((file) => {
    const data = fs.readFileSync(path.join(CORPUS_DIR, file)).toString("base64");
    return c.kind === "pdf"
      ? { type: "document", source: { type: "base64", media_type: "application/pdf", data } }
      : { type: "image", source: { type: "base64", media_type: "image/jpeg", data } };
  });
}

/**
 * Scores one case. Money (cost) rows are tallied into a separate sub-score by the caller.
 * For the non-receipt control only the documentLooksLikeReceipt verdict is scored — prod
 * turns it into the typed not_a_receipt error before any field reaches the client.
 */
function scoreCase(c: GoldenCase, raw: Record<string, unknown>): FieldResult[] {
  const out: FieldResult[] = [];
  const push = (field: string, expected: unknown, got: unknown, pass: boolean) =>
    out.push({ field, expected, got, pass });

  const saidReceipt = raw.documentLooksLikeReceipt !== false;
  push("documentLooksLikeReceipt", c.expect.documentLooksLikeReceipt, saidReceipt,
    saidReceipt === c.expect.documentLooksLikeReceipt);
  if (!c.expect.documentLooksLikeReceipt) return out;

  const proposal = sanitizeReceiptProposal(raw, NOW) as unknown as Record<string, unknown>;

  if (c.expect.entryType !== undefined) {
    push("entryType", c.expect.entryType.join("|"), proposal.entryType,
      c.expect.entryType.includes(String(proposal.entryType)));
  }
  if (c.expect.cost !== undefined) {
    push("cost", c.expect.cost, proposal.cost,
      proposal.cost === c.expect.cost || (c.expect.cost === null && proposal.cost == null));
  }
  if (c.expect.odometerReading !== undefined) {
    push("odometerReading", c.expect.odometerReading, proposal.odometerReading,
      proposal.odometerReading === c.expect.odometerReading ||
      (c.expect.odometerReading === null && proposal.odometerReading == null));
  }
  if (c.expect.shopName !== undefined) {
    const got = typeof proposal.shopName === "string" ? proposal.shopName : null;
    const pass = c.expect.shopName === null
      ? got === null
      : got !== null && got.toLowerCase().includes(String(c.expect.shopName).toLowerCase());
    push("shopName", c.expect.shopName, got, pass);
  }
  if (c.expect.entryDay !== undefined) {
    const got = typeof proposal.entryDate === "string" ? proposal.entryDate.slice(0, 10) : null;
    push("entryDay", c.expect.entryDay, got, got === c.expect.entryDay);
  }
  if (c.expect.isDiy !== undefined) {
    push("isDiy", c.expect.isDiy, proposal.isDiy,
      proposal.isDiy === c.expect.isDiy || (c.expect.isDiy === null && proposal.isDiy == null));
  }
  if (c.expect.lineItemsContain !== undefined && c.expect.lineItemsContain.length > 0) {
    const joined = Array.isArray(proposal.lineItems)
      ? (proposal.lineItems as string[]).join(" | ").toLowerCase()
      : "";
    for (const needle of c.expect.lineItemsContain) {
      push(`lineItems~${needle}`, needle, joined || null, joined.includes(needle.toLowerCase()));
    }
  }
  return out;
}

/**
 * Prompt variants under test. "no-fewshot" is the pre-registered A/B (plan §1): the exemplar
 * is TEXT-transcribed, and whether it transfers to vision is validated here, never assumed.
 * "no-date-line" measures what the anchored system date line is worth on printed documents.
 * "prod-v2" adds the schemaVersion-2 SECOND narrow per-type call (extractReceiptTypedDetails,
 * imported from prod) after a byte-identical call 1, scoring typed fields against the
 * ground-truth table below — the deferred receipt typed ground truth (spec rev-4 header).
 */
const VARIANTS: Record<string, { system: string; fewshot: boolean; typed?: boolean }> = {
  "prod": { system: SYSTEM_PROMPT + referenceDateLine(NOW), fewshot: true },
  "prod-v2": { system: SYSTEM_PROMPT + referenceDateLine(NOW), fewshot: true, typed: true },
  "no-fewshot": { system: SYSTEM_PROMPT + referenceDateLine(NOW), fewshot: false },
  "no-date-line": { system: SYSTEM_PROMPT, fewshot: true },
};

// ---------------------------------------------------------------------------------------------
// Typed ground truth (prod-v2). Values live HERE, not in the generated manifest, so the pinned
// image corpus is never re-rendered for an expectation change. Matchers: null = the model must
// return null (leak check); {sub} = case-insensitive substring; {oneOf} = any listed value
// (null allowed); exact string/number otherwise. Every field of the resolved type's tool is
// scored — fields absent from the map are implicit must-null. A case is scored only when call 1
// resolved the `typedFor` type (dual-accept cases carry one entry per acceptable type); the
// resolution itself is already scored by call 1's entryType row.
// Coverage note: upgradeCategory has no receipt in the pinned corpus (upgrade invoices are not
// in the render set) — recorded as a known gap, not silently skipped: the scoreboard prints it.
// ---------------------------------------------------------------------------------------------

type TypedMatcher = null | string | number | { sub: string } | { oneOf: Array<string | null> };

interface TypedExpectation {
  id: string;
  typedFor: EntryTypeValue;
  fields: Record<string, TypedMatcher>;
}

const TYPED_EXPECTATIONS: TypedExpectation[] = [
  // "0W-20 semi-syn 6 qts" — no oil brand printed anywhere (leak check on brand).
  { id: "clean-dealer", typedFor: "oil_change",
    fields: { brand: null, oilGrade: "0W-20", quantityQuarts: 6 } },
  // Dual-accept sibling: resolved as maintenance, the tool swaps to workItem/nextDueOdometer
  // and "Next service due at 39,218 miles" becomes the one POSITIVE next-due in the corpus.
  { id: "clean-dealer", typedFor: "maintenance",
    fields: { workItem: { sub: "oil" }, nextDueOdometer: 39218 } },
  // "FULL SYNTHETIC 0W-20 / 6 QTS" — again no brand.
  { id: "tall-thermal", typedFor: "oil_change",
    fields: { brand: null, oilGrade: "0W-20", quantityQuarts: 6 } },
  // "MICHELIN DEFENDER2 225/60R17 4 @" — square set: rear may be null or repeat the size.
  // serviceAction accepts null as an ACCEPTED OMISSION, not ground-truth softening: the
  // invoice never names the action — it must be inferred from parts+mounting lines, and the
  // model's anti-fabrication posture nulls rather than guesses (form falls back to its
  // picker). Measured 2026-08-02: an additive prompt illustration moved this 1/5 → 0/5
  // (no benefit, reverted — instructions do not move Haiku; see voice-extraction-fewshot).
  // Revisit only via a receipt few-shot or lineItems-context experiment; named-action
  // receipts (pads, fluid exchange) stay strictly gated below and pass 100%.
  { id: "tire-roadhazard", typedFor: "tire",
    fields: { brand: { sub: "michelin" }, productModel: { sub: "defender" },
      serviceAction: { oneOf: ["new_install", null] }, tireSizeFront: "225/60R17",
      tireSizeRear: { oneOf: [null, "225/60R17"] } } },
  // "DURALAST GOLD PADS" — DIY parts receipt.
  { id: "parts-store", typedFor: "brake",
    fields: { brand: { sub: "duralast" }, serviceAction: "pads_replaced" } },
  // "BRAKE FLUID EXCHANGE" — no parts brand.
  { id: "discount-line", typedFor: "brake",
    fields: { brand: null, serviceAction: "fluid_flush" } },
  // "FRONT BRAKE PADS & ROTORS" — no brand printed.
  { id: "fewshot-anchor", typedFor: "brake",
    fields: { brand: null, serviceAction: { oneOf: ["pads_replaced", "rotors_replaced"] } } },
  // "COOLANT SYSTEM FLUSH" — RO# 118427, phone and ZIP are all mileage-shaped: nextDue TRAP.
  { id: "ro-mileage-trap", typedFor: "maintenance",
    fields: { workItem: { sub: "coolant" }, nextDueOdometer: null } },
  // "TRANSMISSION FLUID SERVICE" — three printed dates, no due mileage: nextDue TRAP.
  { id: "due-date-trap", typedFor: "maintenance",
    fields: { workItem: { sub: "transmission" }, nextDueOdometer: null } },
];

function matcherPasses(matcher: TypedMatcher, got: unknown): boolean {
  if (matcher === null) return got === null || got === undefined;
  if (typeof matcher === "object" && "sub" in matcher) {
    return typeof got === "string" && got.toLowerCase().includes(matcher.sub.toLowerCase());
  }
  if (typeof matcher === "object" && "oneOf" in matcher) {
    return matcher.oneOf.some((v) => (v === null ? got === null || got === undefined : got === v));
  }
  return got === matcher;
}

function scoreTyped(exp: TypedExpectation, details: TypedDetails): FieldResult[] {
  return typedFieldsFor(exp.typedFor).map((field) => {
    const matcher = field in exp.fields ? exp.fields[field] : null;
    const got = details[field] ?? null;
    return {
      field: `typed.${field}`,
      expected: matcher === null ? "null" : JSON.stringify(matcher),
      got,
      pass: matcherPasses(matcher, got),
    };
  });
}

function payloadFor(c: GoldenCase): ReceiptPayload {
  const b64 = (file: string): string =>
    fs.readFileSync(path.join(CORPUS_DIR, file)).toString("base64");
  return c.kind === "pdf"
    ? { kind: "pdf", pdfBase64: b64(c.files[0]) }
    : { kind: "images", images: c.files.map(b64) };
}

async function callModel(
  c: GoldenCase,
  variant: { system: string; fewshot: boolean },
  apiKey: string,
  model: string,
): Promise<Record<string, unknown>> {
  const finalMessage = {
    role: "user",
    content: [
      ...sourceBlocks(c),
      { type: "text", text: "Extract this vehicle service receipt into a log entry." },
    ],
  };
  const response = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: { "content-type": "application/json", "x-api-key": apiKey, "anthropic-version": "2023-06-01" },
    body: JSON.stringify({
      model,
      max_tokens: 1024,
      system: variant.system,
      tools: [RECEIPT_ENTRY_TOOL],
      tool_choice: { type: "tool", name: RECEIPT_ENTRY_TOOL.name },
      messages: variant.fewshot ? [...receiptFewShotMessages(NOW), finalMessage] : [finalMessage],
    }),
  });
  if (!response.ok) {
    // Print ONLY the API's own error message (no request echo, no user data, no headers).
    let apiMessage = "";
    try {
      const body = await response.json() as { error?: { message?: string } };
      apiMessage = typeof body.error?.message === "string" ? ` — ${body.error.message}` : "";
    } catch {
      // body unavailable; status alone will have to do
    }
    throw new Error(`API ${response.status} on ${c.id}${apiMessage}`);
  }
  const payload = await response.json();
  const parsed = toolInputFromPayload(payload);
  if (!parsed) throw new Error(`no tool_use block on ${c.id}`);
  return parsed;
}

async function main(): Promise<void> {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) { console.error("ANTHROPIC_API_KEY not set"); process.exit(1); }
  const variantFlag = process.argv.indexOf("--variant");
  const variant = variantFlag >= 0 ? process.argv[variantFlag + 1] : "prod";
  const spec = VARIANTS[variant];
  if (!spec) { console.error(`unknown variant; use one of: ${Object.keys(VARIANTS).join(", ")}`); process.exit(1); }
  const runsFlag = process.argv.indexOf("--runs");
  const runs = runsFlag >= 0 ? Number(process.argv[runsFlag + 1]) || 1 : 1;
  const modelFlag = process.argv.indexOf("--model");
  const model = modelFlag >= 0 ? process.argv[modelFlag + 1] : "claude-haiku-4-5-20251001";

  const manifest = loadManifest();
  const results: CaseResult[] = [];
  let pass = 0, total = 0;
  let moneyPass = 0, moneyTotal = 0;
  let typedPass = 0, typedTotal = 0, typedSkipped = 0, nullLeaks = 0;
  const perTypedField = new Map<string, { pass: number; total: number }>();
  for (const c of manifest.cases) {
    for (let run = 1; run <= runs; run += 1) {
      const raw = await callModel(c, spec, apiKey, model);
      const fields = scoreCase(c, raw);
      // The v2 second call mirrors prod exactly: the RESOLVED entry type picks the narrow
      // tool, the same source pages are re-sent, and the imported prod function does the rest.
      if (spec.typed && raw.documentLooksLikeReceipt !== false) {
        const proposal = sanitizeReceiptProposal(raw, NOW) as unknown as Record<string, unknown>;
        const resolved = String(proposal.entryType) as EntryTypeValue;
        const exp = TYPED_EXPECTATIONS.find((e) => e.id === c.id && e.typedFor === resolved);
        if (exp) {
          const details = await extractReceiptTypedDetails({
            apiKey, fetchImpl: fetch, payload: payloadFor(c), vehicleLine: "", entryType: resolved,
          });
          const typedRows = scoreTyped(exp, details);
          fields.push(...typedRows);
          for (const row of typedRows) {
            typedTotal += 1;
            if (row.pass) typedPass += 1;
            else if (row.expected === "null") nullLeaks += 1;
            const key = row.field;
            const agg = perTypedField.get(key) ?? { pass: 0, total: 0 };
            agg.total += 1;
            if (row.pass) agg.pass += 1;
            perTypedField.set(key, agg);
          }
        } else if (TYPED_EXPECTATIONS.some((e) => e.id === c.id)) {
          // The case HAS typed truth but call 1 resolved a type we have no entry for — the
          // entryType row already penalised a wrong resolution; this is dual-accept drift.
          typedSkipped += 1;
        }
      }
      results.push({ id: c.id, run, fields, raw });
      for (const field of fields) {
        if (field.field.startsWith("typed.")) continue; // tallied separately above
        total += 1;
        if (field.pass) pass += 1;
        if (field.field === "cost") {
          moneyTotal += 1;
          if (field.pass) moneyPass += 1;
        }
      }
      const casePass = fields.filter((f) => f.pass).length;
      const failed = fields.filter((f) => !f.pass)
        .map((f) => `${f.field}(exp ${JSON.stringify(f.expected)} got ${JSON.stringify(f.got)})`);
      console.log(`${c.id} run${run}: ${casePass}/${fields.length}${failed.length ? "  FAIL " + failed.join(", ") : ""}`);
    }
  }
  const pct = (p: number, t: number): string => (t === 0 ? "n/a" : `${((100 * p) / t).toFixed(1)}%`);
  console.log(`\n[${variant}] TOTAL ${pass}/${total} fields (${pct(pass, total)})`);
  console.log(`[${variant}] MONEY ${moneyPass}/${moneyTotal} cost fields (${pct(moneyPass, moneyTotal)})`);
  if (spec.typed) {
    console.log(`[${variant}] TYPED ${typedPass}/${typedTotal} fields (${pct(typedPass, typedTotal)}), skipped ${typedSkipped} (dual-accept drift), null-leaks ${nullLeaks}`);
    for (const [field, agg] of [...perTypedField.entries()].sort()) {
      console.log(`  ${field}: ${agg.pass}/${agg.total} (${pct(agg.pass, agg.total)})`);
    }
    console.log("  (coverage gap: typed.upgradeCategory — no upgrade invoice in the pinned corpus)");
  }

  const reportDir = path.join(__dirname, "..", "..", "reports");
  fs.mkdirSync(reportDir, { recursive: true });
  const suffix = model === "claude-haiku-4-5-20251001" ? "" : `-${model}`;
  const file = path.join(reportDir, `receipt-golden-${variant}${suffix}.json`);
  fs.writeFileSync(file, JSON.stringify({
    variant, model, runs, now: NOW.toISOString(),
    pass, total, moneyPass, moneyTotal,
    typedPass, typedTotal, typedSkipped, nullLeaks,
    perTypedField: Object.fromEntries(perTypedField), results,
  }, null, 1));
  console.log(`report: ${file}`);

  // ENFORCED gates (prod-v2 only), mirroring the voice eval's machine-checked bar: core must
  // hold the measured pre-v2 baseline (call 1 is byte-identical — any drop is environment or
  // model drift, not this change), every typed field >=0.8 positive-anchored, zero must-null
  // leaks. A miss exits nonzero so no summary prose can soften a failed run.
  if (spec.typed) {
    const failures: string[] = [];
    // 97.5%, not the 98.1% baseline itself: the corpus carries TWO pinned deterministic
    // misreads (skewed-photo odometer 78802, twopage repair→maintenance) that alone cap a
    // clean run at ~98.1%, and at 540 scored fields a single sampling flake moves the total
    // by 0.19% — the floor tolerates one flake, not a new failure class. Money is gated
    // separately and tighter (plan §7's sub-score).
    if (total > 0 && pass / total < 0.975) {
      failures.push(`core ${pct(pass, total)} < 97.5% floor`);
    }
    if (moneyTotal > 0 && moneyPass / moneyTotal < 0.97) {
      failures.push(`money ${pct(moneyPass, moneyTotal)} < 97.0% floor`);
    }
    for (const [field, agg] of perTypedField.entries()) {
      if (agg.total > 0 && agg.pass / agg.total < 0.8) {
        failures.push(`${field} ${pct(agg.pass, agg.total)} < 80%`);
      }
    }
    if (nullLeaks > 0) failures.push(`${nullLeaks} null-expectation leak(s)`);
    if (failures.length > 0) {
      console.error(`\nGATE FAILED: ${failures.join("; ")}`);
      process.exitCode = 1;
    } else {
      console.log("\nGATE PASSED");
    }
  }
}

main().catch((error) => { console.error(error); process.exit(1); });
